//
//  ConvertCurrencyModel.swift
//  ConvertCurrency
//
//  Created by Ahmed Kamal on 09/12/2023.
//

import Foundation

struct ConvertCurrencyModel : Codable {
    let success : Bool?
    let timestamp : Int?
    let base : String?
    let date : String?
    let rates : Rates?
}
struct Rates : Codable {
    let aED : Double?
    let aFN : Double?
    let aLL : Double?
    let aMD : Double?
    let aNG : Double?
    let aOA : Double?
    let aRS : Double?
    let aUD : Double?
    let aWG : Double?
    let aZN : Double?
    let bAM : Double?
    let bBD : Double?
    let bDT : Double?
    let bGN : Double?
    let bHD : Double?
    let bIF : Double?
    let bMD : Double?
    let bND : Double?
    let bOB : Double?
    let bRL : Double?
    let bSD : Double?
    let bTC : Double?
    let bTN : Double?
    let bWP : Double?
    let bYN : Double?
    let bYR : Double?
    let bZD : Double?
    let cAD : Double?
    let cDF : Double?
    let cHF : Double?
    let cLF : Double?
    let cLP : Double?
    let cNY : Double?
    let cOP : Double?
    let cRC : Double?
    let cUC : Double?
    let cUP : Double?
    let cVE : Double?
    let cZK : Double?
    let dJF : Double?
    let dKK : Double?
    let dOP : Double?
    let dZD : Double?
    let eGP : Double?
    let eRN : Double?
    let eTB : Double?
    let eUR : Int?
    let fJD : Double?
    let fKP : Double?
    let gBP : Double?
    let gEL : Double?
    let gGP : Double?
    let gHS : Double?
    let gIP : Double?
    let gMD : Double?
    let gNF : Double?
    let gTQ : Double?
    let gYD : Double?
    let hKD : Double?
    let hNL : Double?
    let hRK : Double?
    let hTG : Double?
    let hUF : Double?
    let iDR : Double?
    let iLS : Double?
    let iMP : Double?
    let iNR : Double?
    let iQD : Double?
    let iRR : Double?
    let iSK : Double?
    let jEP : Double?
    let jMD : Double?
    let jOD : Double?
    let jPY : Double?
    let kES : Double?
    let kGS : Double?
    let kHR : Double?
    let kMF : Double?
    let kPW : Double?
    let kRW : Double?
    let kWD : Double?
    let kYD : Double?
    let kZT : Double?
    let lAK : Double?
    let lBP : Double?
    let lKR : Double?
    let lRD : Double?
    let lSL : Double?
    let lTL : Double?
    let lVL : Double?
    let lYD : Double?
    let mAD : Double?
    let mDL : Double?
    let mGA : Double?
    let mKD : Double?
    let mMK : Double?
    let mNT : Double?
    let mOP : Double?
    let mRU : Double?
    let mUR : Double?
    let mVR : Double?
    let mWK : Double?
    let mXN : Double?
    let mYR : Double?
    let mZN : Double?
    let nAD : Double?
    let nGN : Double?
    let nIO : Double?
    let nOK : Double?
    let nPR : Double?
    let nZD : Double?
    let oMR : Double?
    let pAB : Double?
    let pEN : Double?
    let pGK : Double?
    let pHP : Double?
    let pKR : Double?
    let pLN : Double?
    let pYG : Double?
    let qAR : Double?
    let rON : Double?
    let rSD : Double?
    let rUB : Double?
    let rWF : Double?
    let sAR : Double?
    let sBD : Double?
    let sCR : Double?
    let sDG : Double?
    let sEK : Double?
    let sGD : Double?
    let sHP : Double?
    let sLE : Double?
    let sLL : Double?
    let sOS : Double?
    let sRD : Double?
    let sTD : Double?
    let sYP : Double?
    let sZL : Double?
    let tHB : Double?
    let tJS : Double?
    let tMT : Double?
    let tND : Double?
    let tOP : Double?
    let tRY : Double?
    let tTD : Double?
    let tWD : Double?
    let tZS : Double?
    let uAH : Double?
    let uGX : Double?
    let uSD : Double?
    let uYU : Double?
    let uZS : Double?
    let vEF : Double?
    let vES : Double?
    let vND : Double?
    let vUV : Double?
    let wST : Double?
    let xAF : Double?
    let xAG : Double?
    let xAU : Double?
    let xCD : Double?
    let xDR : Double?
    let xOF : Double?
    let xPF : Double?
    let yER : Double?
    let zAR : Double?
    let zMK : Double?
    let zMW : Double?
    let zWL : Double?
}
